# Generated by Django 3.1.4 on 2021-11-29 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('agent', '0001_initial'),
        ('conversations', '0002_auto_20210329_2000'),
        ('stories', '0001_init')
    ]

    operations = [
        migrations.RunSQL(sql=
            """
                CREATE VIEW users_resources_vw as (

                    SELECT story_id as resource_id, 
                            user_id, 
                            'story' as resource_type
                    FROM stories_storycollaborator

                        UNION
                        
                    SELECT conversation_id as resource_id,
                        presalyticsuser_id as user_id, 
                        'conversation' as resource_type
                    FROM conversations_conversation_participants

                        UNION

                    SELECT team_id as resource_id,
                        user_id,
                        'team' as resource_type
                    FROM teams_teammember

                        UNION
                        
                    SELECT oom.organization_id as resource_id,
                        ooui.presalyticsuser_id as user_id,
                        'organization' as resource_type
                    FROM organization_organizationmember oom
                        INNER JOIN  organization_organizationmember_user_id ooui
                            ON oom.id = organizationmember_id
                            
                        UNION
                        
                    SELECT id as resource_id,
                        user_id as user_id,
                        'agent' as resource_type
                    FROM agent_agent


                );
            """,
            reverse_sql=
            """
            DROP VIEW users_resources_vw;
            """
        )
    ]
