apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    app: workspace-api
    app.kubernetes.io/part-of: workspace
  name: workspace-api
  namespace: api
spec:
  template:
    metadata:
      labels:
        app: workspace-api
        app.kubernetes.io/part-of: workspace
        gitHash: 04360dc6c0ff65cca38b0dcdaf4dd0d37410a6f7
      namespace: api
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: spot
                operator: In
                values:
                - 'true'
            weight: 1
      containers:
      - env:
        - name: DJANGO_DEBUG
          value: 'True'
        - name: DB_REQUIRE_SSL
          value: 'True'
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db-password
              name: workspace
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: db-host
              name: workspace
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: db-user
              name: workspace
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: workspace
        - name: REDIS_HOST
          value: key-value-store.redis.svc.cluster.local
        - name: WORKSPACE_CLIENT_URL
          value: https://workspace.presalytics.io
        - name: DJANGO_SETTINGS_MODULE
          value: api.settings.development
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: api-client-id
              name: workspace
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: api-client-secret
              name: workspace
        - name: ALLOWED_HOSTS
          value: workspace-api.presalytics.io,workspace-api.public.svc.cluster.local,app.presalytics.io,worksapce.api.presalytics.io
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: django-secret-key
              name: workspace
        image: presalytics/workspace-api:latest
        imagePullPolicy: Always
        name: workspace-api
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 128Mi
      tolerations:
      - effect: NoSchedule
        key: kubernetes.azure.com/scalesetpriority
        operator: Equal
        value: spot
