apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    app: workspace
    app.kubernetes.io/part-of: workspace
  name: workspace
  namespace: api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/enable-scale-to-zero: 'false'
        autoscaling.knative.dev/minScale: '1'
      labels:
        app: workspace
        app.kubernetes.io/part-of: workspace
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: spot
                operator: In
                values:
                - 'true'
            weight: 1
      containers:
      - env:
        - name: DJANGO_DEBUG
          value: 'True'
        - name: DB_REQUIRE_SSL
          value: 'True'
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: db
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: db-host
              name: api
        - name: DB_USER
          value: workspace_bot@presalytics_prod
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: workspace
        - name: REDIS_HOST
          value: key-value-store.redis.svc.cluster.local
        - name: WORKSPACE_CLIENT_URL
          value: https://workspace.presalytics.io
        - name: DJANGO_SETTINGS_MODULE
          value: api.settings.development
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: api-client-id
              name: workspace
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: api-client-secret
              name: workspace
        - name: ALLOWED_HOSTS
          value: workspace-api.presalytics.io,workspace-api.api.svc.cluster.local,app.presalytics.io,workspace.api.presalytics.io,workspace.api.svc.cluster.local
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: django-secret-key
              name: workspace
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-storage
              key: connection-string
        image: presalytics/workspace-api:master
        imagePullPolicy: Always
        name: workspace
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 128Mi
      tolerations:
      - effect: NoSchedule
        key: kubernetes.azure.com/scalesetpriority
        operator: Equal
        value: spot
