apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-api
  namespace: public
  labels:
    app: workspace-api
    app.kubernetes.io/name: workspace-api
    app.kubernetes.io/part-of: presalytics
spec:
  selector:
    matchLabels:
      app: workspace-api
      app.kubernetes.io/name: workspace-api
      app.kubernetes.io/part-of: presalytics
  replicas: 1
  template:
    metadata:
      name: workspace-api
      namespace: public
      labels:
        app: workspace-api
        app.kubernetes.io/name: workspace-api
        app.kubernetes.io/part-of: presalytics
    spec:
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      initContainers:
      - name: workspace-migrations
        image: presalytics/workspace-api:latest
        command: ["python3", "manage.py", "migrate"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: DJANGO_DEBUG
          value: 'True'
        - name: DB_REQUIRE_SSL
          value: 'True'
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: workspace
              key: db-password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: workspace
              key: db-host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: workspace
              key: db-user
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: workspace
              key: redis-password
        - name: REDIS_HOST
          value: http://redis.api.svc.cluster.local
        - name: WORKSPACE_CLIENT_URL
          value: https://workspace.presalytics.io
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: workspace
              key: api-client-id
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: workspace
              key: api-client-secret
        - name: DJANGO_SETTINGS_MODULE
          value: api.settings.development
        - name: ALLOWED_HOSTS
          value: workspace-api.presalytics.io
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: workspace
              key: django-secret-key
      containers:
      - name: workspace-api
        image: presalytics/workspace-api:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        ports:
          - containerPort: 80
        env:
        - name: DJANGO_DEBUG
          value: 'True'
        - name: DB_REQUIRE_SSL
          value: 'True'
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: workspace
              key: db-password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: workspace
              key: db-host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: workspace
              key: db-user
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: workspace
              key: redis-password
        - name: WORKSPACE_CLIENT_URL
          value: https://workspace.presalytics.io
        - name: DJANGO_SETTINGS_MODULE
          value: api.settings.development
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: workspace
              key: api-client-id
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: workspace
              key: api-client-secret
        - name: ALLOWED_HOSTS
          value: workspace-api.presalytics.io
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: workspace
              key: django-secret-key
      imagePullSecrets:
      - name: chartalot-docker-registry