# Generated by Django 3.1.4 on 2021-10-26 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=1028)),
                ('type_name', models.CharField(max_length=1028)),
                ('description', models.TextField(max_length=2048)),
                ('source', models.CharField(choices=[('ooxml_automation', 'Ooxml Automation'), ('doc_converter', 'Doc Converter'), ('workpsace', 'Workspace'), ('frontend_app', 'Frontend')], max_length=512)),
                ('default_formatter', models.TextField(max_length=4096)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='eventtypes_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='eventtypes_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
