# Generated by Django 3.1.4 on 2021-03-29 20:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(blank=True, default=None, null=True)),
                ('type', models.CharField(choices=[('slack', 'Slack'), ('teams', 'Ms Teams'), ('bot', 'Bot'), ('gchat', 'Google'), ('salesforce', 'Sf Chatter')], default='bot', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=4096)),
                ('metadata', models.JSONField(blank=True, default=None, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
        ),
    ]
