name: Test-Build-Deploy
on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

# Environment variables available to all jobs and steps in this workflow
env:
  FRONTEND_REGISTRY_NAME: 'presalytics/workspace'
  API_REGISTRY_NAME: 'presalytics/workspace-api'
  CLUSTER_NAME: 'production'
  CLUSTER_RESOURCE_GROUP: 'presalytics-prod'

jobs:
  # test-api:
  #   runs-on: "ubuntu-latest"
  #   env:
  #     DJANGO_SETTINGS_MODULE: api.settings.test
  #     REDIS_PASSWORD: dummy-pass
  #     WORKSPACE_CLIENT_URL: http://test-url
  #     CLIENT_ID: test-client-id
  #     STORY_HOST: https://api.presalytics.io/story/
  #     SITE_HOST: https://presalytics.io/
  #     OOXML_AUTOMATION_HOST: https://api.presalytics.io/ooxml-automation/
  #   defaults:
  #     run:
  #       working-directory: api
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Setup python
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: '3.6.9'
  #   - name: Test
  #     run: |
  #       python -m pip install --upgrade pip
  #       if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  #       python manage.py test
  build-api: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
    - uses: actions/checkout@master
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: presalytics/workspace-api
        tags: |
          type=ref,event=tag
          type=ref,event=branch
          type=sha
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: ./api/Dockerfile
        context: ./api
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: frontend
    env:
      VITE_APP_AUTH0_DOMAIN: login.presalytics.io
      VITE_APP_AUTH0_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      VITE_APP_AUTH0_AUDIENCE: https://api.presalytics.io/
      VITE_APP_I18N_LOCALE: en
      VITE_APP_I18N_FALLBACK_LOCALE: en
      VITE_APP_ENCRYPTION_KEY: ${{ secrets.CLIENT_ENCRYPTION_KEY }}
      VITE_APP_AUTH0_SCOPE: 'email profile offline_acesss'
      VITE_APP_OOXML_AUTOMATION_HOST: https://ooxml-automation.api.presalytics.io
      VITE_APP_EVENTS_HOST: https://events.api.presalytics.io
      VITE_APP_EVENT_STORE_HOST: https://event-store.api.presalytics.io
      VITE_APP_WORKSPACE_HOST: https://workspace.api.presalytics.io
      VITE_APP_HUB_URL: http://events.api.presalytics.io/hub

    steps:
    - uses: actions/checkout@master
    - name: Create .env.production
      run: |
        cd $GITHUB_WORKSPACE
        cd app
        printenv > .env.production
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: presalytics/workspace-frontend
        tags: |
          type=ref,event=tag
          type=ref,event=branch
          type=sha
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: ./app/Dockerfile
        context: ./app
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
  deploy-api:
    if: github.ref == 'refs/heads/master'
    needs: [build-api]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Add git version to manifests
      run: |
        cd $GITHUB_WORKSPACE
        pip3 install gitpython
        python3 scripts/update_hashes.py
    - name: test updates
      run: |
        cd $GITHUB_WORKSPACE
        cat manifests/frontend-service.yaml
    - name: Azure Kubernetes set context
      # https://github.com/Azure/aks-set-context/
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resource-group: presalytics-prod
        cluster-name: production
      id: login
      # https://github.com/Azure/k8s-deploy/
    - name: Deploy to k8s
      uses: Azure/k8s-deploy@v1.4
      with:
        namespace: api
        # Specify what manifest file or files to use - for now, the comms manifest files are in the manifests folder in the comms repo
        manifests: |
          manifests/api-service.yaml

  deploy-frontend:
    if: github.ref == 'refs/heads/master'
    needs: [build-frontend]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Add git version to manifests
      run: |
        cd $GITHUB_WORKSPACE
        pip3 install gitpython
        python3 scripts/update_hashes.py
    - name: test updates
      run: |
        cd $GITHUB_WORKSPACE
        cat manifests/frontend-service.yaml
    - name: Azure Kubernetes set context
      # https://github.com/Azure/aks-set-context/
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resource-group: presalytics-prod
        cluster-name: production
      id: login
      # https://github.com/Azure/k8s-deploy/
    - name: Deploy to k8s
      uses: Azure/k8s-deploy@v1.4
      with:
        namespace: public
        # Specify what manifest file or files to use - for now, the comms manifest files are in the manifests folder in the comms repo
        manifests: |
          manifests/frontend-service.yaml